name: Deploy IPTV Spider

on:
  push:
    branches:
      - main  # 当有代码推送到 main 分支时触发
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点自动触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: your_root_password
          MYSQL_USER: iptv_user
          MYSQL_PASSWORD: your_password
          MYSQL_DATABASE: iptv
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # 设置 Python 版本

      - name: Install Dependencies
        run: |
          pip3 install bs4
          pip3 install m3u8
          pip3 install requests  # 安装依赖

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg  # 安装 FFmpeg

      - name: Run Spider
        run: |
          # 获取 MySQL 服务的连接信息
          MYSQL_HOST=localhost
          MYSQL_USER=iptv_user
          MYSQL_PASSWORD=your_password
          MYSQL_DATABASE=iptv

          # 导出 API_TOKEN
          export API_TOKEN=${{ secrets.API_TOKEN }}
          # 导入数据库结构
          mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < data/iptv_data.sql
          # 运行主程序
          python3 main.py

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: iptv-sources
          path: source/iptv.txt  # 上传生成的文件到 GitHub Actions 的 Artifact
